### ISSUE TITLE
PAL speed not matching original hardware

### ISSUE THREAD

**Issue by MarkEire** [MiSTer-devel/Genesis_MiSTer#188] opened 2021-09-29 19:18 UTC
**Believed similar to current test build fix supplied in SMS core given hardware similarities. I believe "master clock frequency" specific to PAL is required.**
https://github.com/MiSTer-devel/SMS_MiSTer/issues/109#issuecomment-927583787

MiSTer is running faster in PAL mode than my MegaDrive (UK PAL) console. Audibly out of sync in less than one minute, with clear timer differences running Sonic until time expiry (10 minutes), of approximately 6 in game seconds by that point.

- Console: MegaDrive 2, Model MK-1631-50
- MiSTer: Region EU
    - Tested with Miscellaneous -> Rom Storage: Auto, SDRAM, and DDR3 (Border = No)
    - Tested with Border: No, Yes (Rom Storage = Auto)

Speed difference has been observed to be the same regardless of the above MiSTer settings, which I was advised to test by members in the discord chat as useful tests.

**Thanks very much for your time**

**Comment by birdybro** [comment] 2021-11-15 03:20
This is because the PAL clock doesn't seem to be defined the way it is in other emulators.

https://github.com/ekeeke/Genesis-Plus-GX/blob/236e783ec258089a500174e1be550041a4e4850b/core/system.h#L62

Only the NTSC unit's master clock is defined in the MiSTer Core

https://github.com/MiSTer-devel/Genesis_MiSTer/blob/26ad5d2fa75e04146bfdb69b41871381d76f518d/rtl/pll/pll_0002.v#L25

A similar change was was made to the Sega Master System core will need to be made here to address this.

**Comment by birdybro** [comment] 2021-12-16 13:46
@MarkEire Can you please test this build out for me? I tried to fix it. @ArtemioUrbina and @ace9921 have confirmed with MDFourier that it is likely fixed, but want to be sure that it resolves your issue as well. :)

[GenesisPALMCLKTest.zip](https://github.com/MiSTer-devel/Genesis_MiSTer/files/7727742/GenesisPALMCLKTest.zip)

**Comment by sorgelig** [comment] 2021-12-16 14:37
core anyway slightly not matching the speed even if it will use PAL clock. Speed even depends on SDRAM/DDR3 mode.

**Comment by birdybro** [comment] 2021-12-16 15:10
> core anyway slightly not matching the speed even if it will use PAL clock. Speed even depends on SDRAM/DDR3 mode.

Yup, there is also the bus arbitration timing issue that will be resolved one day to address only measurable differences. However Artemio ran MDfourier with some very good results.

My build vs Ace's MEgaDrive, note the bottom right, there is a difference but it is tiny.
![image](https://user-images.githubusercontent.com/16388068/146396851-14e57bf1-ca0d-4213-b8c4-fabd294c1a98.png)

My build vs the current inaccurate timing of the core for PAL (due to it not having a PAL master clock).
![image](https://user-images.githubusercontent.com/16388068/146396986-8f2507c7-fb04-40bd-99a0-8adc8c417951.png)

I'm still going to test more before I submit a PR, I was too quick last time.

**Comment by MarkEire** [comment] 2021-12-16 17:46
Tested the build. With my MiSTer set to AUTO for SDRAM, I have a "MiSTer SDRAM XS-DS v2.9 128MB Module" from misterfpga UK.
Still perfectly in sync (at least as far as I can tell) after over 30 minutes running Sonic 2.

Looks great to me. Thanks very much for the fix!

**Comment by birdybro** [comment] 2021-12-17 17:51
@MarkEire The changes have been merged. Thanks so much for reporting this issue and doing testing! :)

**Closed** 2022-04-18 12:54 UTC
