### ISSUE TITLE
[video] Old Towers, vertical lines on tiles.

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#55] opened 2019-06-13 13:19 UTC
Pressing C, or completeling a level will result in this glitch.

Old Towers can be purchased here:
https://retrosouls.itch.io/old-towers

How the glitch looks:
![20190613_161650](https://user-images.githubusercontent.com/31185814/59435757-f990d300-8df6-11e9-8bfd-2f6a0aeeaee4.jpg)

**Comment by Kitrinx** [comment] 2019-06-13 13:32
This is actually a regression, this behavior was previously fixed by using FIFO quirk, until that was removed when the bus was updated.

**Comment by sorgelig** [comment] 2019-06-13 17:03
I've checked this game at the time i removed the quirk - it was fine that time. 
Which version of Genesis you test: latest release or you compiled the latest changes?

**Comment by James-F2** [comment] 2019-06-13 17:04
Both still have this glitch.
Sometimes it doesn't happen until level 2.

**Comment by sorgelig** [comment] 2019-06-13 17:13
also tested both versions - don't see such problem. played several levels...
strange

**Comment by James-F2** [comment] 2019-06-13 17:25
What version do you have Sorge?

**Comment by sorgelig** [comment] 2019-06-13 17:42
i've tested v1.1 and v1.2 from site. 
Cannot reproduce the problem. Especially on v1.2
It seems Kitrinx also cannot reproduce problem on v1.2.

**Comment by sorgelig** [comment] 2019-06-13 17:43
So it's most likely the bug of game which has been fixed already. Probably it happened on real HW - that's why it's fixed, i guess.

**Comment by James-F2** [comment] 2019-06-13 18:03
v1.2 doesn't glitch on the mister, it's fixed.
v1.1 glitches on level 2 after several C presses.

@Kitrinx 
Was that FIFO related?

**Closed** 2019-06-14 04:45 UTC
